name: Deploy to Production
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "drizzle/**"

jobs:
  deploy:
    name: run database migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run database migration
        run: |
          bun run migrate:run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_MIGRATION_URL }}
